"""Markdown → DOCX conversion pipeline (block parsing + rendering + verify)."""

from .launcher import (
    Block,
    SectionSource,
    parse_markdown,
    add_block,
    add_heading,
    add_body_paragraph,
    add_list_paragraph,
    add_code_block,
    add_equation,
    add_quote,
    add_image,
    add_separator,
    add_table,
    setup_styles,
    make_empty_doc,
    render_blocks_to_doc,
    normalize_text,
    normalize_typography,
    verify_navigation_headings,
    verify_image_relationships,
    verify_clean_review_state,
    convert_unicode_scripts_in_docx,
    document_contains_em_dash,
    document_contains_hyphenated_numeric_range,
)

__all__ = [
    "Block",
    "SectionSource",
    "parse_markdown",
    "add_block",
    "add_heading",
    "add_body_paragraph",
    "add_list_paragraph",
    "add_code_block",
    "add_equation",
    "add_quote",
    "add_image",
    "add_separator",
    "add_table",
    "setup_styles",
    "make_empty_doc",
    "render_blocks_to_doc",
    "normalize_text",
    "normalize_typography",
    "verify_navigation_headings",
    "verify_image_relationships",
    "verify_clean_review_state",
    "convert_unicode_scripts_in_docx",
    "document_contains_em_dash",
    "document_contains_hyphenated_numeric_range",
]