"""DOCX-to-LaTeX export built on the installed Pandoc command."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image

from .._pandoc import run_pandoc

INCLUDE_GRAPHICS_RE = re.compile(
    r"(?P<prefix>\\includegraphics(?:\[[^\]]*\])?\{)(?P<path>[^}]+)(?P<suffix>\})"
)


@dataclass(frozen=True)
class TexExportResult:
    output: Path
    command: tuple[str, ...]
    media: tuple[Path, ...]


def _convert_tiff(path: Path) -> Path:
    if path.suffix.lower() not in {".tif", ".tiff"}:
        return path
    target = path.with_suffix(".png")
    if not target.exists():
        with Image.open(path) as image:
            image.save(target, format="PNG")
    return target


def _find_media(path_value: str, media_root: Path) -> Path | None:
    value = path_value.strip().strip("'\"")
    candidate = Path(value.replace("/", os.sep).replace("\\", os.sep))
    if candidate.exists() and candidate.is_file():
        return candidate
    by_name = media_root / candidate.name
    if by_name.exists() and by_name.is_file():
        return by_name
    for path in media_root.rglob(candidate.name):
        if path.is_file():
            return path
    return None


def _normalise_graphics(body: str, *, output_dir: Path, media_root: Path) -> tuple[str, tuple[Path, ...]]:
    media: set[Path] = set()

    def replace(match: re.Match[str]) -> str:
        source = _find_media(match.group("path"), media_root)
        if source is None:
            return match.group(0)
        rendered = _convert_tiff(source)
        media.add(rendered)
        relative = os.path.relpath(rendered, output_dir).replace(os.sep, "/")
        return f"{match.group('prefix')}{relative}{match.group('suffix')}"

    return INCLUDE_GRAPHICS_RE.sub(replace, body), tuple(sorted(media))


GENERIC_PREAMBLE = r"""\documentclass[12pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{mathptmx}
\usepackage{geometry}
\geometry{a4paper,top=2.54cm,bottom=2.54cm,left=3.17cm,right=3.17cm}
\usepackage{setspace}
\setstretch{1.5}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{xcolor}
\usepackage[normalem]{ulem}
\usepackage{soul}
\usepackage{hyperref}
\setlength{\parindent}{2em}
\setlength{\parskip}{0pt}

"""


def docx_to_tex(
    input_path: Path,
    *,
    output: Path,
    media_dir: Path | None = None,
    track_changes: str = "accept",
    body_only: bool = False,
    force: bool = False,
) -> TexExportResult:
    """Convert a DOCX to LaTeX using Pandoc and a generic preamble."""

    if not input_path.exists():
        raise FileNotFoundError(input_path)
    if output.exists() and not force:
        raise FileExistsError(f"Output exists; pass --force to overwrite: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    extraction_root = media_dir or output.parent
    extraction_root.mkdir(parents=True, exist_ok=True)
    media_root = extraction_root / "media"
    temporary_body = output.with_suffix(output.suffix + ".pandoc")
    if temporary_body.exists():
        temporary_body.unlink()
    try:
        command = run_pandoc(
            input_path,
            temporary_body,
            output_format="latex",
            extract_media_root=extraction_root,
            track_changes=track_changes,
        )
        body = temporary_body.read_text(encoding="utf-8")
        body, media = _normalise_graphics(body, output_dir=output.parent, media_root=media_root)
        generated = body if body_only else (
            "% Auto-generated by docforge docx2tex from "
            f"{input_path.name!r} on {datetime.now(timezone.utc).isoformat()}\n"
            + GENERIC_PREAMBLE
            + "\\begin{document}\n\n"
            + body.strip()
            + "\n\n\\end{document}\n"
        )
        output.write_text(generated, encoding="utf-8")
    finally:
        temporary_body.unlink(missing_ok=True)
    return TexExportResult(output, command, media)


__all__ = ["TexExportResult", "docx_to_tex"]
